
DROP TABLE TRANSACAO;
DROP TABLE AUTORIZACAO;

CREATE TABLE IF NOT EXISTS AUTORIZACAO (
	CODIGO_AUTORIZACAO serial PRIMARY KEY,
	STATUS VARCHAR ( 50 ) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACAO (
	ID serial PRIMARY KEY,
	CARTAO VARCHAR ( 50 ) UNIQUE NOT NULL,
	VALOR INT NOT NULL,
	DATA_HORA TIMESTAMP NOT NULL,
	ESTABELECIMENTO VARCHAR ( 50 ) NOT NULL,
	CODIGO_AUTORIZACAO INT NOT NULL,
	NSU VARCHAR ( 50 ) UNIQUE NOT NULL,
	TIPO VARCHAR ( 50 ) NOT NULL,
	PARCELAS INT NOT NULL,
	FOREIGN KEY(CODIGO_AUTORIZACAO) 
   	REFERENCES AUTORIZACAO(CODIGO_AUTORIZACAO)
);